### ISSUE TITLE
Include suport to set custom connection options (RM #6961)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4728]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6961***
*Originally created by **Israel Lins Albuquerque** at 2021-10-26 13:45:07 UTC.*

This may able to change any option on connection string used by libpq.

**Comment by rafapaisley** [comment]
This feature would be very useful for us as well...
Being able to specify "target_session_attrs=primary" / "target_session_attrs=standby" as in psql or "targetServerType=primary" / "targetServerType=seconday" as in jdbc would be much appreciated

**Comment by dvasdekis** [comment]
Please see issue here: https://github.com/pgadmin-org/pgadmin4/issues/5547
As identified by [adityatoshniwal](https://github.com/adityatoshniwal), adding parameters like `--cluster%3Dgolden-mermaid-3114` would allow connection to CockroachDB Cloud, a free distributed cloud database.
Thanks!

**Comment by nikhil-mohite** [comment]
Getting error on register server with Password file

1. Open the register server dialog, provide basic info name, Host address and enable Kerberos Authentication? (Connect Now? should be enabled )
3. In the Parameters tab add `Password file` field and provide value
4. now click on the save button, getting the following error
<img width="703" alt="image" src="https://user-images.githubusercontent.com/69510038/215097908-8626c320-20be-4be5-9221-915e5ae415be.png">
<img width="794" alt="image" src="https://user-images.githubusercontent.com/69510038/215098004-587f1cbd-7e1d-4617-b13c-7a36f799b177.png">

**Comment by akshay-joshi** [comment]
The issue is fixed.

**Comment by yogeshmahajan-1903** [comment]
While upgrading from pgAdmin 4.15 to latest snapshot, migration is failing with below error.

PFA SS.
<img width="1790" alt="Screenshot 2023-01-30 at 11 42 30 AM" src="https://user-images.githubusercontent.com/16016019/215722877-d3c19ab6-99ce-438a-b5fa-a148c65435ed.png">
```
2023-01-30 11:59:58,604: INFO   pgadmin:        ########################################################
2023-01-30 11:59:58,604: INFO   pgadmin:        Starting pgAdmin 4 v6.19...
2023-01-30 11:59:58,604: INFO   pgadmin:        ########################################################
2023-01-30 11:59:58,605: DEBUG  pgadmin:        Python syspath: ['/Applications/pgAdmin 4.app/Contents/Resources/web', '/Library/Preferences/pgadmin', '/Applications/pgAdmin 4.app/Contents/Resources/web', '/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python39.zip', '/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9', '/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload', '/Applications/pgAdmin 4.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages']
2023-01-30 11:59:58,607: DEBUG  pgadmin:        Available translations: [Locale('pl'), Locale('pt', territory='BR'), Locale('ja'), Locale('it'), Locale('cs'), Locale('ru'), Locale('zh'), Locale('de'), Locale('ko'), Locale('fr'), Locale('es')]
2023-01-30 11:59:58,727: ERROR  pgadmin:        *********
2023-01-30 11:59:58,727: ERROR  pgadmin:        No such constraint: 'ck_ssl_mode'
2023-01-30 11:59:58,727: ERROR  pgadmin:        Exception in database migration.
2023-01-30 11:59:58,727: ERROR  pgadmin:        Creating new database file.
2023-01-30 11:59:59,121: ERROR  pgadmin:        Database migration completed.
```

**Comment by nikhil-mohite** [comment]
> Getting error on register server with Password file
> 
> 1. Open the register server dialog, provide basic info name, Host address and enable Kerberos Authentication? (Connect Now? should be enabled )
> 2. In the Parameters tab add `Password file` field and provide value
> 3. now click on the save button, getting the following error
> 
> <img alt="image" width="703" src="https://user-images.githubusercontent.com/69510038/215097908-8626c320-20be-4be5-9221-915e5ae415be.png">
> 
> <img alt="image" width="794" src="https://user-images.githubusercontent.com/69510038/215098004-587f1cbd-7e1d-4617-b13c-7a36f799b177.png">

This issue is resolved, verified on the latest snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-01-31/
OS: macOS Monterey 12.6
Mode: Desktop mode (Using SQLite db)

**Comment by nikhil-mohite** [comment]
Resolved, Verified on the latest snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-01-31/
OS: macOS Monterey 12.6
Mode: Desktop (Expretal DB Postgres)

**Comment by krisavi** [comment]
> _**Comment migrated from Redmine: https://redmine.postgresql.org/issues/6961#note-12**_ _Originally created by **Allan Nielsen** at 2022-06-06 09:09:24 UTC._
> 
> Hi - Excuse me to clarify my request from 7316 which was rejected. Pgadmin4 connections should have possibility to adress primary in Postgres cluster like this: postgres://hostname1:5432,hostname2:5432/dbname?target_session_attrs=read-write&sslmode=prefer eventually password can be give within same connection string: postgres://username:password@hostname1:5432,hostname2:5432/dbname?target_session_attrs=read-write&sslmode=prefer.
> 
> Regards Allan

It seemed the issue was to support such setups where there are multiple nodes in clusters and it was hijacked by Password file parameter. Initial issue seems still not solved, just the issue that hijacked the initial one was solved.
