### ISSUE TITLE
Browser tree flickering and de-selection issue

### ISSUE THREAD

**Issue by adityatoshniwal** [pgadmin-org/pgadmin4#5559]
Hi,
To reproduce de-selection:
1. Edit a schema to rename it.
2. Upon save, the tree is de-selected but returns a selected item in JS code.

To reproduce the flicker issue,
1. Make sure you have node element with long name which causes horizontal scroll to appear.
4. Scroll to the bottom of the tree in such a way that it just hides the long name node, but horizontal scroll persists.
5. Flickering appears.

![tree-flickr](https://user-images.githubusercontent.com/31855755/203026320-d32ea042-248d-4c3e-ba72-158952115009.gif)

**Comment by nikhil-mohite** [comment]
the de-select issue will get resolved with a fix for #5542, which is already committed.

**Comment by FaharAbbasRizvi** [comment]
The Second issue related to Flickering has been resolved while the tree is de-selected if the user renames the schema name hence, reactivating the case.

**Comment by FaharAbbasRizvi** [comment]
Both issues are resolved  in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-01-06/

**Comment by nl-savills-insightdata** [comment]
In my experience the browser tree flickering on horizontal resize is still present.
Windows 11 H2, pgadmin v6.21
