### ISSUE TITLE
[6.16 / 6.17] import server list doesn't work with external config database

### ISSUE THREAD

**Issue by clockrun** [pgadmin-org/pgadmin4#5620]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

**To Reproduce**

1. use external database for storing config
2. enable OAuth2 login (might be optional step)
3. login and import server from json file

**Expected behavior**
server can be imported and we will see server been added to list

**Error message**

There is no error message, but imported server cannot been seen in server list

**Comment by clockrun** [comment]
Would it because of #5603 ?

here is what happen from my side, with version 6.17
https://user-images.githubusercontent.com/227283/206532133-3bc99b2a-a71c-4980-b13c-30526df20e49.mov

**Comment by akshay-joshi** [comment]
Hi @clockrun 

Can you please test on the snapshot build? Please check the entries into the 'server' table in the external database.

**Comment by clockrun** [comment]
tried yesterday, I failed at logon. will try again today

**Comment by clockrun** [comment]
I have login issue with snapshot, with OAuth enabled. It will prompt me to an empty page, and saying:
```json
{
"success": 0,
"errormsg": "Missing \"jwks_uri\" in metadata",
"info": "",
"result": null,
"data": null
}
```

**Comment by yogeshmahajan-1903** [comment]
@clockrun 
Above issue is fixed as part of #5666. Can you please check with today's snapshot build?

**Comment by kchenery** [comment]
@yogeshmahajan-1903 I still get the error with Google OAuth configured. `6.17` with the same configuration is fine.  With the latest snapshot or `6.18` I get the error above.

**Comment by yogeshmahajan-1903** [comment]
@kchenery 
Could you please confirm which error are you getting?
Also have you tested with this image -  docker pull dpage/pgadmin4:snapshot

**Comment by kchenery** [comment]
Hi @yogeshmahajan-1903,

The error I get is the same above:
```json
{
  "success": 0,
  "errormsg": "Missing \"jwks_uri\" in metadata",
  "info": "",
  "result": null,
  "data": null
}
```

And yes this is with the latest `snapshot` tag.

If I update the image without logging out a session I can use the new version. Its upon login that it occurs (which isnt that surprising).

**Comment by yogeshmahajan-1903** [comment]
Hi @kchenery 
Can you please login in with admin user & check 'OAUTH2_CONFIG' in Help > About dialogue?

**Comment by kchenery** [comment]
Hey @yogeshmahajan-1903 

It shows the configuration for OAUTH as defined:

```
OAUTH2_AUTO_CREATE_USER = True
OAUTH2_CONFIG = [{'OAUTH2_NAME': 'google', 'OAUTH2_DISPLAY_NAME': 'Google', 'OAUTH2_CLIENT_ID': '*********************************************.apps.googleusercontent.com', 'OAUTH2_CLIENT_SECRET': '***********************************', 'OAUTH2_TOKEN_URL': 'https://oauth2.googleapis.com/token', 'OAUTH2_AUTHORIZATION_URL': 'https://accounts.google.com/o/oauth2/auth', 'OAUTH2_API_BASE_URL': 'https://openidconnect.googleapis.com/v1/', 'OAUTH2_USERINFO_ENDPOINT': 'userinfo', 'OAUTH2_SCOPE': 'openid email profile', 'OAUTH2_ICON': 'fa-google', 'OAUTH2_BUTTON_COLOR': '#3253a8'}]
```

Obviously I've hidden the client Id an secret.  This was basically originally copied from the EDB example: https://www.enterprisedb.com/blog/how-configure-oauth-20-pgadmin-4

**Comment by yogeshmahajan-1903** [comment]
> Hey @yogeshmahajan-1903
> 
> It shows the configuration for OAUTH as defined:
> 
> ```
> OAUTH2_AUTO_CREATE_USER = True
> OAUTH2_CONFIG = [{'OAUTH2_NAME': 'google', 'OAUTH2_DISPLAY_NAME': 'Google', 'OAUTH2_CLIENT_ID': '*********************************************.apps.googleusercontent.com', 'OAUTH2_CLIENT_SECRET': '***********************************', 'OAUTH2_TOKEN_URL': 'https://oauth2.googleapis.com/token', 'OAUTH2_AUTHORIZATION_URL': 'https://accounts.google.com/o/oauth2/auth', 'OAUTH2_API_BASE_URL': 'https://openidconnect.googleapis.com/v1/', 'OAUTH2_USERINFO_ENDPOINT': 'userinfo', 'OAUTH2_SCOPE': 'openid email profile', 'OAUTH2_ICON': 'fa-google', 'OAUTH2_BUTTON_COLOR': '#3253a8'}]
> ```
> 
> Obviously I've hidden the client Id an secret. This was basically originally copied from the EDB example: https://www.enterprisedb.com/blog/how-configure-oauth-20-pgadmin-4
> 
> Note: I checked the `snapshot` image and the `6.17` image and they are the same.

`Snapshot` image is of 6.18 version. It means your image is NOT updated in application.
Also additional parameter 'OAUTH2_SERVER_METADATA_URL': should be present in OAUTH2_CONFIG.

**Comment by yogeshmahajan-1903** [comment]
Hi @clockrun ,
Update OAUTH2_CONFIG dict with 'OAUTH2_SERVER_METADATA_URL': 'https://accounts.google.com/.well-known/openid-configuration'.
Then run `kubectl rollout restart deployment` to use updated config by pgAdmin.
If you login with Admin user, you should see below things in About dialogue.

<img width="1075" alt="Screenshot 2022-12-27 at 5 26 47 PM" src="https://user-images.githubusercontent.com/16016019/209663355-7d075afe-3b26-40d0-8265-1866724ebf62.png">

**Comment by kchenery** [comment]
@yogeshmahajan-1903 looks like that missing attribute URL has solved the login issues for the `snapshot` image. Thanks.

**Comment by yogeshmahajan-1903** [comment]
Great!

**Comment by clockrun** [comment]
actually complete function of import / export is not working. When i do export, it generated below file
```json
/pgadmin4 $ cd /var/lib/pgadmin/storage/clockrun_gmail.com/
/var/lib/pgadmin/storage/clockrun_gmail.com $ ls
example.json                 export_server_clockrun.json
/var/lib/pgadmin/storage/clockrun_gmail.com $ cat example.json 
{
    "Servers": {}
/var/lib/pgadmin/storage/clockrun_gmail.com $ 
```
The exported file `example.json` was not in correct json format. Import has similar issue. Test was done on latest snapshot of today.

I enabled external database in this setup. Just did comparison, if I disabled external database, then I can export server list successfully. I guess this new function is causing problem

**Comment by adityatoshniwal** [comment]
@clockrun Can you please share browser console logs? It works fine at our end.

**Comment by clockrun** [comment]
On save, browser sent request
```json
{"filename":"/example.json","type":"export","selected_sever_ids":["117"]}
```
and server respond with 
```json
{
    "success": 1,
    "errormsg": "",
    "info": "",
    "result": null,
    "data": null
}
```
There is no log printed during export server.
But there was error after login into system. Below are complete logs from console
```
DevTools failed to load source map: Could not load content for chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
react_devtools_backend.js:4012 TypeError: Cannot read properties of undefined (reading '_type')
    at Function.a (pgadmin_commons.js?ver=61800:1:10256)
    at e.value (app.bundle.js?ver=61800:2:1284187)
    at e.value (app.bundle.js?ver=61800:2:1283724)
    at new e (app.bundle.js?ver=61800:2:1282814)
    at Function.value (app.bundle.js?ver=61800:2:549880)
    at l (app.bundle.js?ver=61800:2:569003)
    at app.bundle.js?ver=61800:2:569395
    at Et (vendor.others.js?ver=61800:109:2734907)
    at Function.ws (vendor.others.js?ver=61800:109:2769982)
    at app.bundle.js?ver=61800:2:568244
overrideMethod @ react_devtools_backend.js:4012
t @ app.bundle.js?ver=61800:2
(anonymous) @ app.bundle.js?ver=61800:2
63586 @ app.bundle.js?ver=61800:2
f @ app.bundle.js?ver=61800:2
(anonymous) @ app.bundle.js?ver=61800:2
f.O @ app.bundle.js?ver=61800:2
(anonymous) @ app.bundle.js?ver=61800:2
(anonymous) @ app.bundle.js?ver=61800:2
execCb @ require.min.js?ver=61800:9
check @ require.min.js?ver=61800:9
(anonymous) @ require.min.js?ver=61800:9
(anonymous) @ require.min.js?ver=61800:9
(anonymous) @ require.min.js?ver=61800:9
each @ require.min.js?ver=61800:9
emit @ require.min.js?ver=61800:9
check @ require.min.js?ver=61800:9
(anonymous) @ require.min.js?ver=61800:9
(anonymous) @ require.min.js?ver=61800:9
(anonymous) @ require.min.js?ver=61800:9
each @ require.min.js?ver=61800:9
emit @ require.min.js?ver=61800:9
check @ require.min.js?ver=61800:9
enable @ require.min.js?ver=61800:9
init @ require.min.js?ver=61800:9
O @ require.min.js?ver=61800:9
completeLoad @ require.min.js?ver=61800:9
onScriptLoad @ require.min.js?ver=61800:9
load (async)
req.load @ require.min.js?ver=61800:9
load @ require.min.js?ver=61800:9
load @ require.min.js?ver=61800:9
fetch @ require.min.js?ver=61800:9
check @ require.min.js?ver=61800:9
enable @ require.min.js?ver=61800:9
enable @ require.min.js?ver=61800:9
(anonymous) @ require.min.js?ver=61800:9
(anonymous) @ require.min.js?ver=61800:9
each @ require.min.js?ver=61800:9
enable @ require.min.js?ver=61800:9
init @ require.min.js?ver=61800:9
O @ require.min.js?ver=61800:9
completeLoad @ require.min.js?ver=61800:9
onScriptLoad @ require.min.js?ver=61800:9
load (async)
req.load @ require.min.js?ver=61800:9
load @ require.min.js?ver=61800:9
load @ require.min.js?ver=61800:9
fetch @ require.min.js?ver=61800:9
check @ require.min.js?ver=61800:9
enable @ require.min.js?ver=61800:9
enable @ require.min.js?ver=61800:9
(anonymous) @ require.min.js?ver=61800:9
(anonymous) @ require.min.js?ver=61800:9
each @ require.min.js?ver=61800:9
enable @ require.min.js?ver=61800:9
init @ require.min.js?ver=61800:9
O @ require.min.js?ver=61800:9
completeLoad @ require.min.js?ver=61800:9
onScriptLoad @ require.min.js?ver=61800:9
load (async)
req.load @ require.min.js?ver=61800:9
load @ require.min.js?ver=61800:9
load @ require.min.js?ver=61800:9
fetch @ require.min.js?ver=61800:9
check @ require.min.js?ver=61800:9
enable @ require.min.js?ver=61800:9
enable @ require.min.js?ver=61800:9
(anonymous) @ require.min.js?ver=61800:9
(anonymous) @ require.min.js?ver=61800:9
each @ require.min.js?ver=61800:9
enable @ require.min.js?ver=61800:9
init @ require.min.js?ver=61800:9
(anonymous) @ require.min.js?ver=61800:9
setTimeout (async)
req.nextTick @ require.min.js?ver=61800:9
o @ require.min.js?ver=61800:9
requirejs @ require.min.js?ver=61800:9
(anonymous) @ (index):81
require.min.js?ver=61800:9 [Violation] 'load' handler took 834ms
[Violation] Forced reflow while executing JavaScript took 63ms
```

**Comment by pravesh-sharma** [comment]
Hi @clockrun,

We have tried couple of test scenarios but unable to reproduce the issue. Only condition where server.json has `Servers: {}` if from Import/Export we select a server and before click on finish button we remove that server from object explore.

If you have any other steps or details to reproduce this issue please share with us. Also can you please try on the latest version.

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.
