### ISSUE TITLE
The object browser (the tree control tab) disappeared

### ISSUE THREAD

**Issue by iamAnastaisha** [pgadmin-org/pgadmin4#6266]
**Describe the bug**
I've clicked somewhere on the screen and the tree control tab disappeared. I can't find it anywhere...
I was trying to reinstall pgAdmin4 to reset settings, but it didn't work (I even tried different versions and reinstalling PostgreSQL). The settings are saved from the first installation (password too).
On the screenshot below you can see that there is no tree control tab even behind the other tabs.

**To Reproduce**
1. Click on the Tree control tab 
2. Try to move it in different sides

**Expected behavior**
I just want to understand how could I lose this tab, how can I get it back and how to reset settings.

**Screenshots**
![photo_2023-05-09_17-32-34](https://github.com/pgadmin-org/pgadmin4/assets/100077530/50264e8f-3650-4aff-b146-6c3b0b47d91b)

**Desktop:**
 - OS: Windows 10
 - Version: 6.21
 - Mode: Desktop
 - Package type: Python

**Comment by ElStone** [comment]
Similar/same issue is happening with me.  Object Explorer contents suddenly disappear while navigating database tables/other object.  pgAdmin must be restarted to get it to return.

Unable to reliably reproduce, though it is happening often. 

Desktop Version 7.1
Application Mode Desktop
NW.js Version 0.72.0
Browser Chromium 109.0.5414.87
Operating System Windows-10-10.0.22621-SP0

![image](https://github.com/pgadmin-org/pgadmin4/assets/6422934/53052ba9-b15e-4cd5-876d-468b8185b0b1)

**Comment by adityatoshniwal** [comment]
> **Describe the bug** I've clicked somewhere on the screen and the tree control tab disappeared. I can't find it anywhere... I was trying to reinstall pgAdmin4 to reset settings, but it didn't work (I even tried different versions and reinstalling PostgreSQL). The settings are saved from the first installation (password too). On the screenshot below you can see that there is no tree control tab even behind the other tabs.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Click on the Tree control tab
> 2. Try to move it in different sides
> 
> **Expected behavior** I just want to understand how could I lose this tab, how can I get it back and how to reset settings.
> 
> **Screenshots** ![photo_2023-05-09_17-32-34](https://user-images.githubusercontent.com/100077530/237129841-50264e8f-3650-4aff-b146-6c3b0b47d91b.jpg)
> 
> **Desktop:**
> 
> * OS: Windows 10
> * Version: 6.21
> * Mode: Desktop
> * Package type: Python

Hi @iamAnastaisha,

Can you please share the pgadmin4.db file in %APPDATA%/pgadmin4 directory for further investigation?
Meanwhile you can rename pgadmin4.db to pgadmin4.db.bak and restart pgAdmin.

**Comment by adityatoshniwal** [comment]
> Similar/same issue is happening with me. Object Explorer contents suddenly disappear while navigating database tables/other object. pgAdmin must be restarted to get it to return.
> 
> Unable to reliably reproduce, though it is happening often.
> 
> Desktop Version 7.1 Application Mode Desktop NW.js Version 0.72.0 Browser Chromium 109.0.5414.87 Operating System Windows-10-10.0.22621-SP0
> 
> ![image](https://user-images.githubusercontent.com/6422934/238059957-53052ba9-b15e-4cd5-876d-468b8185b0b1.png)

HI @ElStone,

Please share the pgAdmin logs. File->Runtime->View logs.

**Comment by kennytraction** [comment]
@adityatoshniwal I am seeing the same issue as @ElStone. It is very random and I can't seem to reproduce it reliably either. For me it does seem to happen most often when trying to expand a database.

Version: 7.0
Application Mode: Desktop
NW.js Version: 0.72.0
Browser: Chromium 109.0.5414.87
Operating System: Windows-10-10.0.22621-SP0

Here is the UI error from the log file:
```
--------------[UI error]---------------
TypeError: Cannot read properties of undefined (reading 'constructor')
    at h.getItemAtIndex (http://127.0.0.1:60618/static/js/generated/vendor.others.js?ver=70000:109:3001091)
    at getItemKey (http://127.0.0.1:60618/static/js/generated/vendor.others.js?ver=70000:109:3001542)
    at b.render (http://127.0.0.1:60618/static/js/generated/vendor.others.js?ver=70000:109:3434571)
    at Vs (http://127.0.0.1:60618/static/js/generated/vendor.others.js?ver=70000:109:3104328)
    at Qs (http://127.0.0.1:60618/static/js/generated/vendor.others.js?ver=70000:109:3104127)
    at $a (http://127.0.0.1:60618/static/js/generated/vendor.others.js?ver=70000:109:3144914)
    at Tl (http://127.0.0.1:60618/static/js/generated/vendor.others.js?ver=70000:109:3131131)
    at kl (http://127.0.0.1:60618/static/js/generated/vendor.others.js?ver=70000:109:3131059)
    at El (http://127.0.0.1:60618/static/js/generated/vendor.others.js?ver=70000:109:3130922)
    at yl (http://127.0.0.1:60618/static/js/generated/vendor.others.js?ver=70000:109:3127909)
------------[UI End]----------------
```

**Comment by saad-gsoftconsulting** [comment]
Having the same issue with Mac 

MacBook Pro 
OS 13.4 Beta 

![image](https://github.com/pgadmin-org/pgadmin4/assets/133629452/3ae031b4-72d0-4a95-aa3b-7f88a71b82a5)

**Comment by adityatoshniwal** [comment]
HI @saad-gsoftconsulting

Can you please share the pgadmin4.db file in <userhome>/.pgadmin directory for further investigation?

**Comment by ElStone** [comment]
Same UI error as @kennytraction ...

--------------[UI error]---------------
TypeError: Cannot read properties of undefined (reading 'constructor')
    at h.getItemAtIndex (http://127.0.0.1:61729/static/js/generated/vendor.others.js?ver=70100:109:2973263)
    at getItemKey (http://127.0.0.1:61729/static/js/generated/vendor.others.js?ver=70100:109:2973714)
    at b.render (http://127.0.0.1:61729/static/js/generated/vendor.others.js?ver=70100:109:3411134)
    at Qs (http://127.0.0.1:61729/static/js/generated/vendor.others.js?ver=70100:109:3076563)
    at zs (http://127.0.0.1:61729/static/js/generated/vendor.others.js?ver=70100:109:3076362)
    at $a (http://127.0.0.1:61729/static/js/generated/vendor.others.js?ver=70100:109:3117193)
    at Tl (http://127.0.0.1:61729/static/js/generated/vendor.others.js?ver=70100:109:3103415)
    at kl (http://127.0.0.1:61729/static/js/generated/vendor.others.js?ver=70100:109:3103343)
    at El (http://127.0.0.1:61729/static/js/generated/vendor.others.js?ver=70100:109:3103206)
    at yl (http://127.0.0.1:61729/static/js/generated/vendor.others.js?ver=70100:109:3100193)
------------[UI End]----------------

**Comment by PedroMTSilva** [comment]
Hello! I am having exactly the same issue. After i moved the tree control tab acidentally, now i can't find it anywhere. I also can't open some of the other windows, like, "add new server" option on the dashboard. I tried uninstalling everything, i tried resetting the layout, but it wont even let me do that because the prompt box to confirm the layout reset wont even open.

I am currently using:

OS: Pop_OS! 
Version: jammy LTS 22.04

**Comment by yogeshmahajan-1903** [comment]
Shared a db file over email when this issue is reproduced.

**Comment by losk90** [comment]
io ho lo stesso problema 
non mi permette di visualizzare la barra superiore

**Comment by adityatoshniwal** [comment]
Hi,

This is fixed with pgAdmin v7.2 released today.

Thanks.

**Comment by EFrankel-ITEP** [comment]
It's not fixed. Happened to me this morning with 7.3. I had a table expanded and Columns expanded under that. I noticed that the arrow icon indicating expanded state on the table was pointing the wrong way and I was unable to collapse the table. I right-clicked on Tables and selected Refresh to get it to reset and the Object Explorer disappeared.

**Comment by EFrankel-ITEP** [comment]
I have steps to reproduce:
1. Expand a table
2. Right-click the table and select Count Rows
3. Note that the expanded indicator switches to the wrong direction
4. Object Explorer will disappear soon after this.  Count Rows again, Refresh Tables, etc. to trigger it.

**Comment by bonkzwonil** [comment]
same issue here, with v 7.4

**Comment by adityatoshniwal** [comment]
> It's not fixed. Happened to me this morning with 7.3. I had a table expanded and Columns expanded under that. I noticed that the arrow icon indicating expanded state on the table was pointing the wrong way and I was unable to collapse the table. I right-clicked on Tables and selected Refresh to get it to reset and the Object Explorer disappeared.

@EFrankel-ITEP,
Just realised, the issue you mentioned is #5306 and not related to this issue. Both are different. I will link back your steps to the appropriate issue.
Thanks.

**Comment by FaharAbbasRizvi** [comment]
I have verified this issue on the latest snapshot build and the issue seems to be fixed.

@bonkzwonil @ElStone 

Can you please try once on the latest snapshot build? 

https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-06-21/

**Comment by FaharAbbasRizvi** [comment]
@EFrankel-ITEP 

Before closing this issue I want a confirmation message from the user, I will be closing this issue tomorrow. kindly confirm once on the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-06-22/

**Comment by EFrankel-ITEP** [comment]
@FaharAbbasRizvi: I'm pushing a deadline right now, but I'll shake some time loose this afternoon to pull the snapshot build.

**Comment by EFrankel-ITEP** [comment]
@FaharAbbasRizvi: Does not appear fixed. I pulled and installed https://ftp.postgresql.org/pub/pgadmin/pgadmin4/snapshots/2023-06-21/pgadmin4-7.3-x64.exe. Same behavior. With a table expanded, Count Rows causes the expansion indicator to flip in the wrong direction. A half dozen or so more Count Rows and Tables>Refresh causes the Explorer to go blank.

**Comment by EFrankel-ITEP** [comment]
@FaharAbbasRizvi: Bug appears fixed fixed. The expansion indicator no longer flips when using Count Rows, although the expanded elements do flicker as if the tree branch is being rebuilt. I am no longer able to cause the Explorer to corrupt or go blank.

**Comment by FaharAbbasRizvi** [comment]
This is tested in the latest snapshot build and the user has also verified this and I am closing the issue.

**Comment by t0d0r** [comment]
Hi, I'm facing same issue, Object explorer disappear when I'm opening database with huge scheme list switching between production and stage databases and start scrolling with scroller or using mouse wheel. 
It not happens every time to be reproduced easily. 
Object Explorer reappear by using Reset Layout , but in that case you lose all of the opened tabs and should start from  the beginning.

```
--------------[UI error]---------------
TypeError: Cannot read properties of undefined (reading 'constructor')
    at d.getItemAtIndex (http://127.0.0.1:52898/static/js/generated/vendor.others.js?ver=70700:109:3135068)
    at getItemKey (http://127.0.0.1:52898/static/js/generated/vendor.others.js?ver=70700:109:3135519)
    at b.render (http://127.0.0.1:52898/static/js/generated/vendor.others.js?ver=70700:109:3574303)
    at Qs (http://127.0.0.1:52898/static/js/generated/vendor.others.js?ver=70700:109:3238368)
    at zs (http://127.0.0.1:52898/static/js/generated/vendor.others.js?ver=70700:109:3238167)
    at Ga (http://127.0.0.1:52898/static/js/generated/vendor.others.js?ver=70700:109:3278998)
    at Tl (http://127.0.0.1:52898/static/js/generated/vendor.others.js?ver=70700:109:3265220)
    at kl (http://127.0.0.1:52898/static/js/generated/vendor.others.js?ver=70700:109:3265148)
    at El (http://127.0.0.1:52898/static/js/generated/vendor.others.js?ver=70700:109:3265011)
    at yl (http://127.0.0.1:52898/static/js/generated/vendor.others.js?ver=70700:109:3261998)
------------[UI End]----------------
```

```
ALLOW_SAVE_PASSWORD = True
ALLOW_SAVE_TUNNEL_PASSWORD = False
APP_COPYRIGHT = "Copyright (C) 2013 - 2023, The pgAdmin Development Team"
APP_ICON = "pg-icon"
APP_NAME = "pgAdmin 4"
APP_RELEASE = 7
APP_REVISION = 7
APP_SUFFIX = ""
APP_VERSION = "7.7"
APP_VERSION_EXTN = ('.css', '.js', '.html', '.svg', '.png', '.gif', '.ico')
APP_VERSION_INT = 70700
APP_VERSION_PARAM = "ver"
AUTHENTICATION_SOURCES = ['internal']
AUTO_DISCOVER_SERVERS = True
AZURE_CREDENTIAL_CACHE_DIR = "C:\Users\ANONYMISED\AppData\Roaming\pgadmin\azurecredentialcache"
CA_FILE = "C:\Program Files\pgAdmin 4\v7\web\cacert.pem"
CHECK_EMAIL_DELIVERABILITY = False
CHECK_SESSION_FILES_INTERVAL = 24
CHECK_SUPPORTED_BROWSER = True
COMPRESS_LEVEL = 9
COMPRESS_MIMETYPES = ['text/html', 'text/css', 'text/xml', 'application/json', 'application/javascript']
COMPRESS_MIN_SIZE = 500
CONFIG_DATABASE_CONNECTION_MAX_OVERFLOW = 100
CONFIG_DATABASE_CONNECTION_POOL_SIZE = 5
CONFIG_DATABASE_URI = ""
CONSOLE_LOG_FORMAT = "%(asctime)s: %(levelname)s	%(name)s:	%(message)s"
CONSOLE_LOG_LEVEL = 30
CONTENT_SECURITY_POLICY = "default-src ws: http: data: blob: 'unsafe-inline' 'unsafe-eval';"
COOKIE_DEFAULT_DOMAIN = None
COOKIE_DEFAULT_PATH = "/"
DATA_DIR = "C:\Users\ANONYMISED\AppData\Roaming\pgadmin"
DEBUG = False
DEFAULT_BINARY_PATHS = {'pg': '$DIR/../runtime', 'ppas': ''}
DEFAULT_SERVER = "127.0.0.1"
DEFAULT_SERVER_PORT = 5050
DESKTOP_USER = "pgadmin4@pgadmin.org"
DISABLED_LOCAL_PASSWORD_STORAGE = False
EFFECTIVE_SERVER_PORT = 52898
ENABLE_BINARY_PATH_BROWSING = False
ENABLE_PSQL = True
ENHANCED_COOKIE_PROTECTION = True
FILE_LOG_FORMAT = "%(asctime)s: %(levelname)s	%(name)s:	%(message)s"
FILE_LOG_LEVEL = 30
HELP_PATH = "../../../docs/en_US/html/"
IS_WIN = True
KERBEROS_CCACHE_DIR = "C:\Users\ANONYMISED\AppData\Roaming\pgadmin\krbccache"
KEYRING_NAME = "Windows WinVaultKeyring"
KRB_APP_HOST_NAME = "127.0.0.1"
KRB_AUTO_CREATE_USER = True
KRB_KTNAME = "<KRB5_KEYTAB_FILE>"
LANGUAGES = {'en': 'English', 'zh': 'Chinese (Simplified)', 'cs': 'Czech', 'fr': 'French', 'de': 'German', 'id': 'Indonesian', 'it': 'Italian', 'ja': 'Japanese', 'ko': 'Korean', 'pl': 'Polish', 'pt_BR': 'Portuguese (Brazilian)', 'ru': 'Russian', 'es': 'Spanish'}
LDAP_ANONYMOUS_BIND = False
LDAP_AUTO_CREATE_USER = True
LDAP_BASE_DN = "<Base-DN>"
LDAP_BIND_FORMAT = "{LDAP_USERNAME_ATTRIBUTE}={LDAP_USERNAME},{LDAP_BASE_DN}"
LDAP_BIND_USER = None
LDAP_CA_CERT_FILE = ""
LDAP_CERT_FILE = ""
LDAP_CONNECTION_TIMEOUT = 10
LDAP_DN_CASE_SENSITIVE = False
LDAP_KEY_FILE = ""
LDAP_SEARCH_BASE_DN = "<Search-Base-DN>"
LDAP_SEARCH_FILTER = "(objectclass=*)"
LDAP_SEARCH_SCOPE = "SUBTREE"
LDAP_SERVER_URI = "ldap://<ip-address>:<port>"
LDAP_USERNAME_ATTRIBUTE = "<User-id>"
LDAP_USE_STARTTLS = False
LOGIN_ATTEMPT_FIELDS = ['password']
LOGIN_BANNER = ""
LOG_FILE = "C:\Users\ANONYMISED\AppData\Roaming\pgadmin\pgadmin4.log"
LOG_ROTATION_AGE = 1440
LOG_ROTATION_MAX_LOG_FILES = 90
LOG_ROTATION_SIZE = 10
MAIL_DEBUG = False
MAIL_PORT = 25
MAIL_SERVER = "localhost"
MAIL_USERNAME = ""
MAIL_USE_SSL = False
MAIL_USE_TLS = False
MASTER_PASSWORD_HOOK = None
MASTER_PASSWORD_REQUIRED = True
MAX_LOGIN_ATTEMPTS = 3
MAX_QUERY_HIST_STORED = 20
MAX_SESSION_IDLE_TIME = 60
MFA_EMAIL_SUBJECT = None
MFA_ENABLED = False
MFA_FORCE_REGISTRATION = False
MFA_SUPPORTED_METHODS = ['email', 'authenticator']
MODULE_BLACKLIST = ['test']
NODE_BLACKLIST = []
OAUTH2_AUTO_CREATE_USER = True
OAUTH2_CONFIG = [{'OAUTH2_NAME': None, 'OAUTH2_DISPLAY_NAME': '<Oauth2 Display Name>', 'OAUTH2_CLIENT_ID': None, 'OAUTH2_CLIENT_SECRET': None, 'OAUTH2_TOKEN_URL': None, 'OAUTH2_AUTHORIZATION_URL': None, 'OAUTH2_SERVER_METADATA_URL': None, 'OAUTH2_API_BASE_URL': None, 'OAUTH2_USERINFO_ENDPOINT': None, 'OAUTH2_SCOPE': None, 'OAUTH2_USERNAME_CLAIM': None, 'OAUTH2_ICON': None, 'OAUTH2_BUTTON_COLOR': None, 'OAUTH2_ADDITIONAL_CLAIMS': None}]
ON_DEMAND_RECORD_COUNT = 1000
OVERRIDE_USER_INACTIVITY_TIMEOUT = True
PASSWORD_LENGTH_MIN = 6
PG_DEFAULT_DRIVER = "psycopg3"
PROXY_X_FOR_COUNT = 1
PROXY_X_HOST_COUNT = 0
PROXY_X_PORT_COUNT = 1
PROXY_X_PREFIX_COUNT = 0
PROXY_X_PROTO_COUNT = 1
SECURITY_EMAIL_SENDER = "no-reply@localhost"
SECURITY_EMAIL_SUBJECT_PASSWORD_CHANGE_NOTICE = "Your password for pgAdmin 4 has been changed"
SECURITY_EMAIL_SUBJECT_PASSWORD_NOTICE = "Your pgAdmin 4 password has been reset"
SECURITY_EMAIL_SUBJECT_PASSWORD_RESET = "Password reset instructions for pgAdmin 4"
SECURITY_EMAIL_VALIDATOR_ARGS = {'check_deliverability': False}
SEND_FILE_MAX_AGE_DEFAULT = 31556952
SERVER_HEARTBEAT_TIMEOUT = 30
SERVER_MODE = False
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_NAME = "pga4_session"
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = False
SESSION_DB_PATH = "C:\Users\ANONYMISED\AppData\Roaming\pgadmin\sessions"
SESSION_EXPIRATION_TIME = 7
SESSION_SKIP_PATHS = ['/misc/ping']
SETTINGS_SCHEMA_VERSION = 35
SHARED_STORAGE = []
SHOW_GRAVATAR_IMAGE = True
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLITE_PATH = "C:\Users\:ANONYMISED\AppData\Roaming\pgadmin\pgadmin4.db"
SQLITE_TIMEOUT = 500
STORAGE_DIR = "C:\Users\ANONYMISED\AppData\Roaming\pgadmin\storage"
STRICT_TRANSPORT_SECURITY = "max-age=31536000; includeSubDomains"
STRICT_TRANSPORT_SECURITY_ENABLED = False
SUPPORT_SSH_TUNNEL = True
TEST_SQLITE_PATH = "C:\Users\ANONYMISED\AppData\Roaming\pgadmin\test_pgadmin4.db"
THREADED_MODE = True
UPGRADE_CHECK_ENABLED = True
UPGRADE_CHECK_KEY = "pgadmin4"
UPGRADE_CHECK_URL = "https://www.pgadmin.org/versions.json"
USER_INACTIVITY_TIMEOUT = 0
WEBSERVER_AUTO_CREATE_USER = True
WEBSERVER_REMOTE_USER = "REMOTE_USER"
WEB_SERVER = "Python"
WTF_CSRF_HEADERS = ['X-pgA-CSRFToken']
X_CONTENT_TYPE_OPTIONS = "nosniff"
X_FRAME_OPTIONS = "SAMEORIGIN"
X_XSS_PROTECTION = "1; mode=block"
```

**Comment by t0d0r** [comment]
@FaharAbbasRizvi , forgot to mention you, did I need to open new issue about it?
