### ISSUE TITLE
Please enter a value for the parameter

### ISSUE THREAD

**Issue by gumuliokas** [pgadmin-org/pgadmin4#6489]
Got error message when trying to edit OLD connection for database. The error message is: "Please enter a value for the parameter".
If there are empty parameter - I would like to know which one. But the connection works fine, its connects to DB. But when i trie to i.e. rename the connection or add a comment - i cannot save, because of that error.

![image](https://github.com/pgadmin-org/pgadmin4/assets/15009387/71713277-e3dc-4abd-813f-75432f5132be)
 
The error comes possibly from migrated older pgadmin versions to newer, but from pgdmin 4. Not pgadmin 3.
Also in pgadmin4.log file there nothing for that case

pgAdmin 4, version 7.3 from pgadmin.org
Application mode: Desktop
Windows 10

**Comment by akshay-joshi** [comment]
@gumuliokas 

Can you please check the 'Parameters' tab?

**Comment by mfaheemakhtar** [comment]
I am facing a similar issue while renaming the connection. It updated the host without any issues.

![image](https://github.com/pgadmin-org/pgadmin4/assets/17894982/5bf11b13-9e24-4427-a7a2-474f1f784dc6)

**Comment by tebbutp** [comment]
I'm having the same issue

**Comment by gumuliokas** [comment]
> @gumuliokas
> 
> Can you please check the 'Parameters' tab?

![image](https://github.com/pgadmin-org/pgadmin4/assets/15009387/6bbdd8a1-4093-4ebd-a5e0-d804dcf8b4c7)
This is parameter tab.

**Comment by gumuliokas** [comment]
![image](https://github.com/pgadmin-org/pgadmin4/assets/15009387/f40ac5e1-ee4d-4449-8440-d4ad34fbde92)
connection tab

**Comment by gumuliokas** [comment]
Okay, i have managed to remove in parameter tab empty value in "host address". And it worked. I still got error message editing this one, connection name:
![image](https://github.com/pgadmin-org/pgadmin4/assets/15009387/e42488dd-87cf-48d4-b101-91d015fa5191)

**Comment by gumuliokas** [comment]
This time it generate logs:
2023-06-29 13:07:18,792: ERROR	pgadmin:	pgAdmin4
Traceback (most recent call last):
  File "C:\Program Files\pgAdmin 4\v7\web\pgadmin\browser\server_groups\servers\__init__.py", line 887, in update
    keyring.delete_password(KEY_RING_SERVICE_NAME,
  File "C:\Program Files\pgAdmin 4\v7\python\lib\site-packages\keyring\core.py", line 65, in delete_password
    get_keyring().delete_password(service_name, username)
  File "C:\Program Files\pgAdmin 4\v7\python\lib\site-packages\keyring\backends\Windows.py", line 150, in delete_password
    raise PasswordDeleteError(service)
keyring.errors.PasswordDeleteError: pgAdmin4
2023-06-29 13:07:18,792: ERROR	pgadmin:	'PasswordDeleteError' object has no attribute 'message'
Traceback (most recent call last):
  File "C:\Program Files\pgAdmin 4\v7\web\pgadmin\browser\server_groups\servers\__init__.py", line 887, in update
    keyring.delete_password(KEY_RING_SERVICE_NAME,
  File "C:\Program Files\pgAdmin 4\v7\python\lib\site-packages\keyring\core.py", line 65, in delete_password
    get_keyring().delete_password(service_name, username)
  File "C:\Program Files\pgAdmin 4\v7\python\lib\site-packages\keyring\backends\Windows.py", line 150, in delete_password
    raise PasswordDeleteError(service)
keyring.errors.PasswordDeleteError: pgAdmin4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\pgAdmin 4\v7\python\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\pgAdmin 4\v7\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Program Files\pgAdmin 4\v7\python\lib\site-packages\flask\views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "C:\Program Files\pgAdmin 4\v7\web\pgadmin\browser\utils.py", line 311, in dispatch_request
    return method(*args, **kwargs)
  File "C:\Program Files\pgAdmin 4\v7\python\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Program Files\pgAdmin 4\v7\web\pgadmin\browser\server_groups\servers\__init__.py", line 894, in update
    errormsg=e.message
AttributeError: 'PasswordDeleteError' object has no attribute 'message'

**Comment by FaharAbbasRizvi** [comment]
This is fixed in the latest snapshot:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-07-19

**Comment by lzambarda** [comment]
This problem is still happening to me on version 8.5
I tried to connect to a database but I had an issue with the port number. This error is now preventing me from apply any changes!

**Comment by chylek-qr** [comment]
> This problem is still happening to me on version 8.5 I tried to connect to a database but I had an issue with the port number. This error is now preventing me from apply any changes! The only solution for me was to restart pgAdmin and edit the server without trying to connect to it.

I can't do that, because the moment I expand the server group, pgAdmin immediately connects to the database...

**Comment by bcmlee** [comment]
I also had the same issue. I solved the problem by first disconnecting from the server, then edit the properties by removing the Host Address row from the Parameters tab.

**Comment by yogeshmahajan-1903** [comment]
@chylek-qr 
Can you please share logs and exact reproduction steps?

**Comment by bcmlee** [comment]
@chylek-qr, you can prevent the auto-expand by going to File -> Preferences -> Browser -> Display, and disable "Auto-expand sole children".

Also, even after connecting to the server, you can simply disconnect it (by right-clicking on it and select 'Disconnect from server'), and then edit the properties.

**Comment by chylek-qr** [comment]
> Also, even after connecting to the server, you can simply disconnect it (by right-clicking on it and select 'Disconnect from server'), and then edit the properties.

It's been several months so I don't remember exactly what happened, but I don't think I was able to just disconnect from the server. Maybe it wouldn't let me out of the dialog, not sure. Thanks for the tip to disable auto-expanding sole children.

> I guess you have original issue again. Hence I asked for reproduction steps that.

Unfortunately I don't know the reproduction steps. I had been using pgAdmin for several years and upgraded it over time. After I updated to 8.12, I ran into the bug, and found this thread with another person confirming that it's still an issue in 8.x.

These are the only logs from the day I searched for this error:

```
2024-10-20 21:02:14,293: WARNING	werkzeug:	Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.
2024-10-20 21:04:13,181: WARNING	werkzeug:	Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.
2024-10-20 21:04:41,715: WARNING	werkzeug:	Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.
2024-10-20 21:05:52,480: ERROR	pgadmin:	Manager not found. Stopped Heartbeat logging for the session id: b3dbb9e3-3479-4f01-b865-4672d02cee8f and server id: 3
```
