### ISSUE TITLE
Setting "Use spaces?" stopped working

### ISSUE THREAD

**Issue by brsa** [pgadmin-org/pgadmin4#7269]
One more broken item in the Query Tool for v8.4 - a follow up to https://github.com/pgadmin-org/pgadmin4/issues/7268

There is the option "Use spaces?"
> Specifies whether or not to insert spaces instead of tabs when the tab key or auto-indent are used.

Used to work and insert spaces instead of tabs. Now the setting seems to be ignored and (unwanted) tabs are inserted.

**Comment by casparsch** [comment]
I have the same experience.

Some additional information:
If a tab-_character_ is selected and again the tab-_key_ is pressed **this** tab is expanded to spaces.
Furthermore the tabs-to-spaces is underneath the "SQL Formatting". This _could_ be interpreted as applicable only when: "Format SQL" (Ctrl-Shift-K) is invoked. It is a subtle difference but I _assume_ one does not want to distinguish between **editing** and **formatting** a query.
Found the property (tabs-to-spaces) only being used when looking into the pgAdmin code on the event of the "Format SQL". _At least for what I understood from it._ On no other places I could find this property.

**Comment by pravesh-sharma** [comment]
The issue is still reproducible on the latest snapshot build.

**Comment by adityatoshniwal** [comment]
> The issue is still reproducible on the latest snapshot build.

I couldn't reproduce this on latest source code.  Attaching screen recording.

https://github.com/pgadmin-org/pgadmin4/assets/31855755/d78a6f91-29fb-44ef-ab01-56d72ecd1c38

**Comment by pravesh-sharma** [comment]
Attaching behaviour from version 8.3 if `use spaces?` is enabled pressing backspace used to clear space only right now it is clearing entire tab character. On pressing the arrow keys it works.

https://github.com/pgadmin-org/pgadmin4/assets/111979571/97771622-2f7c-42ac-9bac-8d85c4f1efcc

**Comment by adityatoshniwal** [comment]
> Attaching behaviour from version 8.3 if `use spaces?` is enabled pressing backspace used to clear space only right now it is clearing entire tab character. On pressing the arrow keys it works.
> 
>  Screen.Recording.2024-03-23.at.12.06.02.PM.mov

Are you expecting to replace all the tabs with spaces when "Use spaces" is used? If yes, then that's absurd. Once a tab is pressed, on backspace a tab will be removed. Use spaces means from here on it will use spaces for tabs.

**Comment by pravesh-sharma** [comment]
> > Attaching behaviour from version 8.3 if `use spaces?` is enabled pressing backspace used to clear space only right now it is clearing entire tab character. On pressing the arrow keys it works.
> > Screen.Recording.2024-03-23.at.12.06.02.PM.mov
> 
> Are you expecting to replace all the tabs with spaces when "Use spaces" is used? If yes, then that's absurd. Once a tab is pressed, on backspace a tab will be removed. Use spaces means from here on it will use spaces for tabs.

No. I have attached only the previous behaviour and if the current one is the correct then we can ignore.

**Comment by adityatoshniwal** [comment]
> No. I have attached only the previous behaviour and if the current one is the correct then we can ignore.
I just tested v8.2, it has the same behaviour like the new. No matter use spaces is enabled or not, existing tabs are not replaced with spaces even in old.

**Comment by pravesh-sharma** [comment]
> > No. I have attached only the previous behaviour and if the current one is the correct then we can ignore.
> 
> I just tested v8.2, it has the same behaviour like the new. No matter use spaces is enabled or not, existing tabs are not replaced with spaces even in old.

I am not saying it should replace the existing tabs with space. I am talking about behaviour on the backspace. We can connect offline and I can show you what exactly I mean.

**Comment by pravesh-sharma** [comment]
The issue has been resolved. Verified on snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-03-27/).

**Comment by brsa** [comment]
While version 8.5 now inserts spaces when pressing the [tab] key as set up in the preferences (thank you!), some issues remain:

1. With "Use spaces?" enabled, pressing [tab] always inserts a **constant number** of spaces (3 in my case).

2. On a new line, or with only tabs and spaces before the cursor, pressing [backspace] deletes back a **variable number** of spaces (or one tab character) to align with the previous tab position. That changes after the first non-space character in the line: then [backspace] deletes back exactly one character.

This is the exact opposite of how it should be:

1. Pressing [tab] should insert space characters to align on the next multiple of tab width.

2. Pressing [backspace] should always delete exactly on character. No matter what.

**Comment by adityatoshniwal** [comment]
> While version 8.5 now inserts spaces when pressing the [tab] key as set up in the preferences (thank you!), some issues remain:
> 
> 1. With "Use spaces?" enabled, pressing [tab] always inserts a **constant number** of spaces (3 in my case).

Can't reproduce. It adds spaces based on preference.

> 2. On a new line, or with only tabs and spaces before the cursor, pressing [backspace] deletes back a **variable number** of spaces (or one tab character) to align with the previous tab position. That changes after the first non-space character in the line: then [backspace] deletes back exactly one character.
> 
> This is the exact opposite of how it should be:
> 
> 1. Pressing [tab] should insert space characters to align on the next multiple of tab width.
> 2. Pressing [backspace] should always delete exactly one character. No matter what.

This is a default behaviour in most of standard IDEs. I guess we'll need to add more preferences for Editor. Check my comment here - https://github.com/pgadmin-org/pgadmin4/issues/7317#issuecomment-2029678440

**Comment by brsa** [comment]
> > While version 8.5 now inserts spaces when pressing the [tab] key as set up in the preferences (thank you!), some issues remain:
> > 
> > 1. With "Use spaces?" enabled, pressing [tab] always inserts a **constant number** of spaces (3 in my case).
> 
> Can't reproduce. It adds spaces based on preference.

Pressing [tab] should align at the next tab position - whether with a single tab character or the required number of spaces. Currently, with "Use spaces?" enabled, a fixed number of spaces is entered, alignment is not observed. This is just wrong. But maybe the work done in #7317 also takes care of this? I'll have to hope for version 8.6 ...

**Comment by adityatoshniwal** [comment]
@brsa You don't need to wait for the 8.6 release to test this. You can test with daily nightly builds generated here - https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/

**Comment by casparsch** [comment]
> While version 8.5 now inserts spaces when pressing the [tab] key as set up in the preferences (thank you!), some issues remain:
> 
> 1. With "Use spaces?" enabled, pressing [tab] always inserts a **constant number** of spaces (3 in my case).
> 2. On a new line, or with only tabs and spaces before the cursor, pressing [backspace] deletes back a **variable number** of spaces (or one tab character) to align with the previous tab position. That changes after the first non-space character in the line: then [backspace] deletes back exactly one character.
> 
> This is the exact opposite of how it should be:
> 
> 1. Pressing [tab] should insert space characters to align on the next multiple of tab width.
> 2. Pressing [backspace] should always delete exactly one character. No matter what.

Waited for release 8.6 to verify.
This issue is actually already mentioned in release 8.5, to be resolved.

**Comment by akshay-joshi** [comment]
@casparsch 

v8.6 has already been released yesterday.

**Comment by casparsch** [comment]
> @casparsch
> 
> v8.6 has already been released yesterday.

I know, I already installed it. As also stated in my comment: "... this is **not** the case in 8.6."

**Comment by brsa** [comment]
With "Use spaces?" activated, pressing [tab] does not align at the next tab position, as reported. The bug is still present in version 8.6.

Reopen this one or create a new issue?

**Comment by adityatoshniwal** [comment]
> With "Use spaces?" activated, pressing [tab] does not align at the next tab position, as reported. The bug is still present in version 8.6.
> 
> Reopen this one or create a new issue?

Hi,
Can you explain what exactly is the issue? May be with some screenshot or recording?

**Comment by brsa** [comment]
It's very simple. How can there be misunderstanding?
Pressing the [tab] key does not align at the next tab position, which is the actual purpose of the [tab] key.

To reproduce, activate "Use spaces?" with "Tab size" = 3 (for example). Then, in the query tool:
- Press [tab] → 3 spaces are entered
- On the next line, enter 1 character, then press [tab] → still 3 spaces are entered, but it should be 2 spaces to align at position 3
- On the next line, enter 2 characters, then press [tab] → still 3 spaces are entered, but it should be 1 space to align at position 3

```
-- expected:
   |
1  |
12 |
123   |
1234  |

-- status quo:
   |
1   |
12   |
123   |
1234   |
```

I am running Ubuntu Ubuntu 20.04.6 LTS. This is what "About pgAdmin4" dumps:

Version 8.6
Application Mode Desktop
Current User pgadmin4@pgadmin.org
NW.js Version 0.77.0
Browser Chromium 114.0.5735.91
Operating System Linux-5.15.0-105-generic-x86_64-with-glibc2.29
pgAdmin Database File /home/erwin/.pgadmin/pgadmin4.db
Log File /home/erwin/.pgadmin/pgadmin4.log

**Comment by adityatoshniwal** [comment]
> It's very simple. How can there be misunderstanding?
Probably because English is not my first language and don't hold any literature degree in English.

**Comment by adityatoshniwal** [comment]
@brsa  Anyway, you can create a separate ticket with details you just mentioned.

**Comment by casparsch** [comment]
Maybe this will clarify things: [tabs (history)](https://typographyforlawyers.com/tabs-and-tab-stops.html)
By reading the first paragraph I think it supports what brsa stated.

_Yes, it at least goes back to the typewriter era, like other concepts (at least the "carriage", "return", "linefeed" and even the "bell"). The bell (physically present) was to signal the typist he or she was near the end of the line.
So tabs back then were a specific position for the carriage to slide to. These positions could arbitrarily selected/set by the typist._

In case of editors for coding nowadays it is widely accepted (even expected) to have the cursor going to the next position to the multiple of "the number the spaces" as configured (the width of the tab).
For instance take a look at editors like Notepad++ (windows), geany (linux), sublime (linux). Even Notepad from microsoft itself, though it does not have the option to fill with spaces or set the width, it aligns to the same position on the horizontal line.

**Comment by brsa** [comment]
> @brsa Anyway, you can create a separate ticket with details you just mentioned.

Done! :)
https://github.com/pgadmin-org/pgadmin4/issues/7486
