### ISSUE TITLE
Custome Role

### ISSUE THREAD

**Issue by HeartConnector** [pgadmin-org/pgadmin4#7310]
Let's add custom roles

**Comment by khushboovashi** [comment]
Hi @HeartConnector, can you be more specific here as Login roles can be created from the UI (See Login/Group Roles from left side tree node)?

**Comment by HeartConnector** [comment]
For example  https://github.com/dbeaver/cloudbeaver/wiki/Users

**Comment by anilsahoo20** [comment]
Related to #1632.

**Comment by AndrewJackson2020** [comment]
+1 for this feature. Would love to have more locked down users who are not able to register new servers for example.

**Comment by IreneKnapp** [comment]
I would also like to register my interest in this, for that same use-case.

**Comment by yogeshmahajan-1903** [comment]
Issues found while testing - 
1.User is not able to remove server in desktop mode - 

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/5bb547b3-0d13-4a4f-ba62-dc27eb3644a9" />
(this is reason for all feature failures)

2.

**Comment by adityatoshniwal** [comment]
@yogeshmahajan-1903  I've fixed the above mentioned issues except the 2nd one. I leave it to the administrator to manage permission instead of pgAdmin handling it.

**Comment by yogeshmahajan-1903** [comment]
From review comments below still are not fixed - 
1.If there is no Query Tool permission then Create Script, Generate Script(from Schema Diff) should also shown the Permission Denied pop up.
2.Checkboxes on the permissions tab look disabled when not selected. Can we change the background color to white?
3.Disable the Query Tool and PSQL Tool workspace if there is no permission.

**Comment by adityatoshniwal** [comment]
> From review comments below still are not fixed -
1.If there is no Query Tool permission then Create Script, Generate Script(from Schema Diff) should also shown the Permission Denied pop up.
Create script shows the pop up, generate script fixed.
2.Checkboxes on the permissions tab look disabled when not selected. Can we change the background color to white? 
I have update the checkbox border color. The background color is in consistency with all other places.

3.Disable the Query Tool and PSQL Tool workspace if there is no permission.
The permission denied pop-up is thrown currently to tell the user of missing permission.

**Comment by yogeshmahajan-1903** [comment]
This is working fine.
