### ISSUE TITLE
Failed to decrypt the saved password

### ISSUE THREAD

**Issue by amirhossein-deriv** [pgadmin-org/pgadmin4#9258]
Describe the bug

We upgraded our pgAdmin to V9.3, now there are two kind of issues:

the saved password for one user gets error:
Failed to decrypt the saved password. Error: 'utf-8' codec can't decode byte 0xaf in position 1: invalid start byte

and

Failed to decrypt the saved password. Error: 'utf-8' codec can't decode byte Oxd5 in position 0: invalid continuation byte
to solve this issue regarding our online research we find these links helpful and based on them we cleared the passwords for all connections and setup them.

https://www.pgadmin.org/docs/pgadmin4/9.3/clear_saved_passwords.html
https://stackoverflow.com/questions/56526882/pgadmin-error-failed-to-decrypt-the-saved-password

We have the second issue that raised after the other one:
connection failed: connection to server at "xx.xx.xx.xx", port 5432 failed: fe_sendauth: no password supplied
To Reproduce

upgrade version 8.12 to 9.3
See the error
Expected behavior

Regarding the issue posted from older versions, it should be solved and don't raise again.

Error message

Failed to decrypt the saved password. Error: 'utf-8' codec can't decode byte 0xaf in position 1: invalid start byte

Failed to decrypt the saved password. Error: 'utf-8' codec can't decode byte Oxd5 in position 0: invalid continuation byte

Screenshots

<img width="1216" height="562" alt="Image" src="https://github.com/user-attachments/assets/c9b7744b-af6a-4242-8cdb-fe712e0d950f" />

<img width="623" height="291" alt="Image" src="https://github.com/user-attachments/assets/327ad57d-1438-4134-8263-8be085ee47d0" />
Docker:

image: dpage/pgadmin4:9.3
Version: [e.g. 6.15]
Mode: [e.g Desktop or Server]
Browser: chrome
Package type: Container

sharing below our pgadmin info

Version 9.5
Application Mode Server
Commit a5714903acb250481a987f3e352680b7a66403b5 2025-06-27
Python Version 3.12.11
Browser Chrome 139.0.0.0
Operating System Alpine Linux v3.22, Linux-5.10.0-35-cloud-amd64-x86_64-with
pgAdmin Database File /var/lib/pgadmin/pgadmin4.db
And this is our PgAdmin Docker compose file

version: '3.7'
services:
  pgadmin:
    image: dpage/pgadmin4:9.5
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: 4G
    ports:
      - 8001:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=<REDACTED>
      - PGADMIN_DEFAULT_PASSWORD=<REDACTED>
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False
      - PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT=False
    volumes:
      - type: bind
        source: /data/pgadmin
        target: /var/lib/pgadmin
      - type: bind
        source: /data/pgadmin/servers.json
        target: /pgadmin/servers.json
please do let us know if anything else we can provide to help replicating this

unsolved lssue:
https://github.com/pgadmin-org/pgadmin4/issues/8776
https://github.com/pgadmin-org/pgadmin4/issues/5487

**Comment by yogeshmahajan-1903** [comment]
@amirhossein-deriv 
Can you please share the Docker logs that were printed during the upgrade? Also, if possible, can you please share dummy passwords which has special characters that are being used in the actual password? 

Also, please try with the latest pgadmin version.

**Comment by amirhossein-deriv** [comment]
@yogeshmahajan-1903
I attached the logs and the dummy password is: AhQwY!eT0y00nRxh5PDO%qA&gAD$fsSRQ6N

[pgAdminlogs.txt](https://github.com/user-attachments/files/22965395/pgAdminlogs.txt)

**Comment by skel0** [comment]
Same problem here using pgAdmin 9.8, master password enabled and oauth2 authentication using Entra ID.

**Comment by Lxrdknows77** [comment]
Same bug. Basically as temp solution we switched to non-shared server connection per user. Few hours investigetions didn't help.

**Comment by mbtx2** [comment]
We are also having this same issue.  Been going for a while.  I suspect that it has something to do with special characters in password.  Just a guess, since not everyone experiences it.  Perhaps some auto-generated passwords use characters that won't work in utf-8.  We are on 9.8.

**Comment by nptrainor** [comment]
Version 9.9
I have the same problem of not begin able to save the password - it is making PgAdmin **UNUSABLE** for me.
**The password I use is all lower case, is made up of characters from a-z only.**

2025-10-21 14:03:03,702: ERROR  pgadmin:    'utf-8' codec can't decode byte 0xcc in position 0: invalid continuation byte
Traceback (most recent call last):
  File "/usr/pgadmin4/web/pgadmin/utils/driver/psycopg3/connection.py", line 257, in _decode_password
    password = password.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcc in position 0: invalid continuation byte

Using Desktop App on Fedora.

**Comment by lightvik** [comment]
Some our users confirm this bug on version 9.9, password haven't special symbols.
downgrade to 9.4 help resolve problem.

**Comment by neonlight911** [comment]
v9.9 - have the same issue

**Comment by yogeshmahajan-1903** [comment]
> [@yogeshmahajan-1903](https://github.com/yogeshmahajan-1903) I attached the logs and the dummy password is: AhQwY!eT0y00nRxh5PDO%qA&gAD$fsSRQ6N
> 
> [pgAdminlogs.txt](https://github.com/user-attachments/files/22965395/pgAdminlogs.txt)

@amirhossein-deriv 
I am not able to reproduce the issue. Are you using OAuth2 for authentication? The logs shared by you does not have any error.
If possible could you please share complete docker config?

**Comment by yogeshmahajan-1903** [comment]
> Same problem here using pgAdmin 9.8, master password enabled and oauth2 authentication using Entra ID.

@skel0 
Is the problem arises after upgrades to 9.8 or it was in previous version too? What was pgadmin version where this was working for you.  Are facing same issue with newly added server? Can you please try clearing password for existing server and again save it and try recoonecting?

**Comment by yogeshmahajan-1903** [comment]
> going for a while. I suspect that it has something to do with special characters in password. Just a guess, since not everyone experiences it. Perhaps some auto-generated passwords use characters that won't work in utf-8. We are on 9.8.

@mbtx2 
Can you please share some dummy passwords from users for who this does not work?

**Comment by yogeshmahajan-1903** [comment]
> Version 9.9 I have the same problem of not begin able to save the password - it is making PgAdmin **UNUSABLE** for me. **The password I use is all lower case, is made up of characters from a-z only.**
> 
> 2025-10-21 14:03:03,702: ERROR pgadmin: 'utf-8' codec can't decode byte 0xcc in position 0: invalid continuation byte Traceback (most recent call last): File "/usr/pgadmin4/web/pgadmin/utils/driver/psycopg3/connection.py", line 257, in _decode_password password = password.decode() UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcc in position 0: invalid continuation byte
> 
> Using Desktop App on Fedora.

@nptrainor 
Does pgadmin prompts you for master password?

**Comment by amirhossein-deriv** [comment]
@yogeshmahajan-1903 in the  version we are using it is not prompting for master password

**Comment by mbtx2** [comment]
> > going for a while. I suspect that it has something to do with special characters in password. Just a guess, since not everyone experiences it. Perhaps some auto-generated passwords use characters that won't work in utf-8. We are on 9.8.
> 
> [@mbtx2](https://github.com/mbtx2) Can you please share some dummy passwords from users for who this does not work?

I'm not sure it's the password characters anymore, given that some of those who are experiencing the issue in this issue thread have no special characters.  I should point out that we are now on 9.9 using server version.  I'll see if we can narrow it down to a specific dummy password that is reproducible.

**Comment by yogeshmahajan-1903** [comment]
> [@yogeshmahajan-1903](https://github.com/yogeshmahajan-1903) in the version we are using it is not prompting for master password

I think in that case, you are using an internal authentication source as internal in which case the login password is the master password. Can you please try adding new server and try with saved password? Does it give you the same behaviour? Kindly tun on debug log level and sahre logs for further debugging.

**Comment by amirhossein-deriv** [comment]
@yogeshmahajan-1903
behavior is the same and this is the log when other user wants to login to the shared server

2025-10-31 09:38:32,375: ERROR	pgadmin:	'utf-8' codec can't decode byte 0xc2 in position 0: invalid continuation byte
Traceback (most recent call last):
  File "/pgadmin4/pgadmin/utils/driver/psycopg3/connection.py", line 255, in _decode_password
    password = password.decode()
               ^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 0: invalid continuation byte
2025-10-31 09:38:32,378: ERROR	pgadmin:	Could not connect to server(#3) - 'localpsql'.
Error: Failed to decrypt the saved password.
Error: 'utf-8' codec can't decode byte 0xc2 in position 0: invalid continuation byte

**Comment by Guiorgy** [comment]
If the password is not too sensitive (could change it later) you could try executing the following inside the container:

```shell
sed -i 's|"Failed to decrypt the saved password\.\\nError: {0}"|"Failed to decrypt the saved password\.\\nError: {0}\\nPassword: {1}"|g; s|)\.format(str(e)), password|)\.format(str(e), password.hex()), password|g' /pgadmin4/pgadmin/utils/driver/psycopg3/connection.py
```

This will include the password bytes as a hex string in the log.

**Comment by yogeshmahajan-1903** [comment]
@amirhossein-deriv 
Have other users who are facing issues changed their server password after adding/saving the **shared** server password?

**Comment by nptrainor** [comment]
Just to say, I'm now using version 9.11 on Fedora and the problem has seemingly been resolved. For me at least. 

Thank you for your hard work. It is much appreciated.

Nick

**Comment by amirhossein-deriv** [comment]
No @yogeshmahajan-1903, they did not.

**Comment by yogeshmahajan-1903** [comment]
@amirhossein-deriv 
I am not able to reproduce issue with shared server too. 
1.Can you please share complete continuer config file?
2.What is pgadmin version are you using?
3.Does this issue happens only for shared server? If yes then, is it for user who is using shared server?

I could reproduce the issue only if shared server user has changed their login password.

**Comment by skel0** [comment]
Hi, 

Even the question is not for me, just wanted to share also how this error looks like in our side. 
We use shared servers and it is happening to all users. We have configured master password. Till know only have seen in shared server, but we mainly use them, indeed we have restricted the users to create/modify servers. I would say only happen opening Query Tool, I don't remember to have seen when connecting and browsing the database schemas and objects. The owner of the shared servers is Administrator and we don't use it to connect to the databases, we use our domain users to connect, so I don't know if also has the problem or not. If you want, I can do some testing and come later to you, since the error is not happening all time.
Just upgraded today to 9.11 (running on podman over RHEL 9.7) but was failing in 9.10.

If I can help in any other way, please let me know.

BTW, sorry because I missed your question some time back. I think it has been failing since I started with pgadmin web server (I think was 9.1 the fist one I installed), for all versions. till 9.10.

**Comment by svedatbegar** [comment]
The issue still exists for us, even using 9.11 version. We have OAuth login set up, but we have internal auth enabled as well. The OAuth users set up their own master password, then they enter the DB passwords, and it works for a while until it does not and we haven't been able to find the trigger. Resetting the master password and re-entering the DB passwords again fixes it temporarily until it happens again. Using the internal authentication method I could login in an incognito window, and I surely can navigate the query tools and send queries. In our experience, the problem is only tied to OAuth users.

Interestingly, I can navigate the "Object Explorer" on the left side of the dashboard and get results for that using my OAuth user. For example, I can open a dropdown menu there for "Sequences", and I see the loading icon and the results are retrieved. And I haven't opened that dropdown before, I can see it loading and requesting the information the first time so I'm not seeing cached results. This means that the authentication to the database works, but for some reason, it doesn't work on the query tools. Currently I cannot run any query, but I can see the skeleton of the database and how it's structured.

**Comment by skel0** [comment]
Confirmed on our side too: an user just reported the issue a while ago, few hours after the upgrade to 9.11

**Comment by amirhossein-deriv** [comment]
@yogeshmahajan-1903

1.Can you please share complete continuer config file?
The config files are shared in the beginning thread and is the same for us.

2.What is pgadmin version are you using?
The version we are using is 9.5, and we stopped upgrading because every time we had same issue and users were suffering.

3.Does this issue happens only for shared server? If yes then, is it for user who is using shared server?
I afraid if i could not understand the meaning of shared server,  we installed it on k8s, and as container on standalone VM and we see same issue. 
To clarify, we have two users one is in administrator role that we create and share the servers and one in user role that they can use shared server by administrator.

**Comment by auroraeosrose** [comment]
Same issue 

Current version 9.11

1. "admin" user creates server and saves password - admin user is NOT using ldap login but just an internal login - and shares server
2. secondary user - who IS using an ldap login - tries to access server and gets error 

<img width="577" height="282" alt="Image" src="https://github.com/user-attachments/assets/09fab0af-7f9b-419f-b74e-2a3e8ab945f6" />

we saw this problem before - removing the encrypted password and redoing it as admin user fixed the problem

But I tried that and it does not work in 9.11

Logs show

```
2026-01-02 13:49:43,850: ERROR  pgadmin:        'utf-8' codec can't decode byte 0xfd in position 0: invalid start byte
Traceback (most recent call last):
  File "/usr/pgadmin4/web/pgadmin/utils/driver/psycopg3/connection.py", line 257, in _decode_password
    password = password.decode()                                                                                        UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 0: invalid start byte
```

**Comment by pravesh-sharma** [comment]
Issue fixed. Verified on latest snapshot build.

**Comment by rafik-gassara** [comment]
still having the same issue on v9.12

<img width="689" height="344" alt="Image" src="https://github.com/user-attachments/assets/bfb9fa0c-02f9-4c94-947e-1331372da85f" />

<img width="817" height="525" alt="Image" src="https://github.com/user-attachments/assets/84d73c84-2f01-4ce9-89b0-852e8a4a11c1" />

**Comment by Rarasinhoo** [comment]
Started a clean container with the docker image dpage/pgadmin4:9.12 and the issue still persists for all my users...

I started the container fresh with internal login enabled, logged in in the default account gave admin to my oauth user, and then deleted internal user and disabled internal method.
After this, to reproduce you will need 2 users, log in with the user A and save your password, it will work fine, then log in in the user B and save the password on the same server.
After this, password of user A might be corrupt. Another thing a noticed, is that even the username or the first user is lost or overwritten by the second user.

All my users log in only with Microsoft Entra ID.

For me, the issue started happening with some v8 update, and happens on every single one, all the way up to 9.12.

**Comment by pravesh-sharma** [comment]
Hi @Rarasinhoo,

Can you please share the error you are getting?

**Comment by Rarasinhoo** [comment]
![Image](https://github.com/user-attachments/assets/32b30fc0-75b5-477c-9295-c5a72e394844)

This is the error, note that this is not my database user, it was overwritten by the second user 

1) I save my user and password in a shared server, everything works fine
2) User B saves it's user and password on the same shared server
3) I see the user B database username on my screen, and the error

Looks like only one user can save a password on a server

**Comment by RohitBhati8269** [comment]
Working fine. Tested on the latest snapshot build.

**Comment by meeftah** [comment]
> ![Image](https://github.com/user-attachments/assets/32b30fc0-75b5-477c-9295-c5a72e394844)
> 
> This is the error, note that this is not my database user, it was overwritten by the second user
> 
> 1. I save my user and password in a shared server, everything works fine
> 2. User B saves it's user and password on the same shared server
> 3. I see the user B database username on my screen, and the error
> 
> Looks like only one user can save a password on a server

I have the same case

**Comment by RohitBhati8269** [comment]
@meeftah, on which pgAdmin version did you check?
As the issue is fixed and will be available in the upcoming release.

**Comment by svedatbegar** [comment]
This unfortunately still does not work for our case. Tested with version 9.13.

The steps to reproduce:
1. Enable both internal and OAuth users in the initial configuration.
2. Login with the internal user, enter database passwords and make them shared.
3. Logout.
4. Login with the OAuth user, enter master password.
5. Select the database you shared in step 2, able to view the schema.
6. Select a table and try to use the query tool for it.
7. It asks for the password, enter the DB password (the same one entered in step 2).
8. Get the following error:<img width="752" height="382" alt="Image" src="https://github.com/user-attachments/assets/d826241c-0539-451d-a348-5fb9c354f625" />

**Comment by lenin-sk** [comment]
version 9.13.0 too having the same issue.

**Comment by MarekKrempa** [comment]
Encountered this issue today on version 9.12

Found workaround: 
1. Select 'Clear Saved Password' in DB connection context menu
2. Logout OAuth user
3. Login OAuth user
4. Connect to server by entering the password

**Comment by meeftah** [comment]
so far so good after updating, but I will keep continue testing with my team

**Comment by lenin-sk** [comment]
@meeftah what was the version you been using ? any workaround you have applied ?

**Comment by meeftah** [comment]
@lenin-sk I'm using pgadmin v9.13, no workaround has been made but I'm still testing to see whether the bug still exists or not. But maybe you can try to clean saved password first for all of account that you have then fill username and password based on the logged account

**Comment by pravesh-sharma** [comment]
> version 9.13.0 too having the same issue.

Hi @lenin-sk I am not able to reproduce the issue can you please try clearing the saved password and then try again.

**Comment by svedatbegar** [comment]
> Encountered this issue today on version 9.12
> 
> Found workaround:
> 
> 1. Select 'Clear Saved Password' in DB connection context menu
> 2. Logout OAuth user
> 3. Login OAuth user
> 4. Connect to server by entering the password

That only works temporarily. I cleared the password on OAuth user, logged out and logged back in and the queries worked. Then I logged out and logged in with the initial internal user again. This time, I got the same error for the internal user, and when I tried to enter the DB password for the internal user it failed repeatedly, it does not even accept the correct DB password. I need to clear it again, logout and log back in for it to work.

It feels like settings on one user (internal) affects the others (OAuth users) and vice versa.

**Comment by meeftah** [comment]
> > Encountered this issue today on version 9.12
> > Found workaround:
> > 
> > 1. Select 'Clear Saved Password' in DB connection context menu
> > 2. Logout OAuth user
> > 3. Login OAuth user
> > 4. Connect to server by entering the password
> 
> That only works temporarily. I cleared the password on OAuth user, logged out and logged back in and the queries worked. Then I logged out and logged in with the initial internal user again. This time, I got the same error for the internal user, and when I tried to enter the DB password for the internal user it failed repeatedly, it does not even accept the correct DB password. I need to clear it again, logout and log back in for it to work.
> 
> It feels like settings on one user (internal) affects the others (OAuth users) and vice versa.

have you update to the latest version and try it out?

**Comment by svedatbegar** [comment]
> have you update to the latest version and try it out?

Yes, I've tried it out with version 9.13 with the same results.

**Comment by meeftah** [comment]
> > have you update to the latest version and try it out?
> 
> Yes, I've tried it out with version 9.13 with the same results.

So, I think the best solution for this case is each of user add manually each of the connection and set do not share among users so that connection belong to that user only

**Comment by pravesh-sharma** [comment]
Hi @svedatbegar,

Can you please share the steps to reproduce the issue, I am not able to reproduce on the latest version.

**Comment by svedatbegar** [comment]
I've shared the steps to reproduce it above.

> The steps to reproduce:
> 
> 1. Enable both internal and OAuth users in the initial configuration.
> 2. Login with the internal user, enter database passwords and make them shared.
> 3. Logout.
> 4. Login with the OAuth user, enter master password.
> 5. Select the database you shared in step 2, able to view the schema.
> 6. Select a table and try to use the query tool for it.
> 7. It asks for the password, enter the DB password (the same one entered in step 2).
> 8. Get the following error:

We can ask everyone to create their own DB without sharing them and that could possibly work, but that would sort of defeat the purpose of shared databases.

**Comment by realhuseyn** [comment]
the same issue

**Comment by pravesh-sharma** [comment]
Hi @svedatbegar and @realhuseyn,

We have fixed the issue in latest version of pgAdmin as a part of #9789.

**Comment by svedatbegar** [comment]
Thanks, upgrading to version 9.14 fixed the issue for us.

**Comment by skel0** [comment]
Hello, 

I am running v9.15 and still see this error when selecting "View/Edit Data" for any table and then choose any of the options like "All Rows", "First 100 Rows", ...

<img width="627" height="259" alt="Image" src="https://github.com/user-attachments/assets/bb260d66-6a71-4cd4-af46-c0759a508c4e" />

**Comment by amcs99** [comment]
I use Windows, and even upgrading to version 9.14 or 9.15 didn't work for me. However, after clearing the app data, it seems to be working now. Here is what I did:
**NOTE:** This will remove your current database credentials in pgAdmin.
1. Press **Windows + R**, type `%appdata%`, and hit Enter.
2. Locate the `pgAdmin` and `pgadmin4` folders.
3. Delete all data from those two folders and reopen the program.

**Comment by skel0** [comment]
Thanks @amcs99 for sharing this. But in my case, I still get the same error after following these steps. I am running v9.15 

<img width="1141" height="485" alt="Image" src="https://github.com/user-attachments/assets/ff363f6f-0326-4a37-896b-c913a95dc85c" />

**Comment by nubbeldupp** [comment]
I had someone with the same issue... Connect successful after entering the password but got "Failed to decrypt saved password" when trying to "View Data".

What helped in this case was clearing the saved password. 

<img width="284" height="203" alt="Image" src="https://github.com/user-attachments/assets/8feb4fce-b7c0-4aec-886d-e167e11c3f52" />

After that he was able to connect and save the password again. So far no issues.

**Comment by skel0** [comment]
Thanks @nubbeldupp for the information. In our case, don't know why, even performing "Clear Saved Password" the issue is not getting resolved.

@pravesh-sharma would it be possible to re-open the issue to fix it completely?

Kind regards.
