### ISSUE TITLE
Cannot Update on a Read-Only Volume [pgAdmin v9.9] [macOS Sequoia 15.5]

### ISSUE THREAD

**Issue by matthewbordas** [pgadmin-org/pgadmin4#9402]
**Describe the bug**

- I'm unable to install the latest update to v9.10
- I click download and then it displays an error when trying to run it
- People [reference this](https://github.com/Squirrel/Squirrel.Mac/issues/182#issuecomment-3417902629) from the Squirrel repo and mention having issues with pgAdmin
- They also filed a [newer issue](https://github.com/Squirrel/Squirrel.Mac/issues/291)

**To Reproduce**

1. Check for updates
2. Download the v9.10 update
3. Confirm it shows an error

**Expected behavior**

- It should install the update successfully

**Error message**

```zsh
Error: Cannot update while running on a read-only volume.
The application is on a read-only volume. Please move the application and try again.
If you're on macOS Sierra or later, you'll need to move the application out of the Downloads directory.
See https://github.com/Squirrel/Squirrel.Mac/issues/182 for more information.
```

**Screenshots**

<img width="812" height="161" alt="Image" src="https://github.com/user-attachments/assets/33974932-d725-4bbe-a426-cb00f937025c" />

**Desktop (please complete the following information):**

 - OS: `macOS Sequoia 15.5`
 - pgAdmin version: `v9.9`
 - Mode: `Desktop`
 - Browser: `N/A` 
 - Package type: `N/A`

**Additional context**

N/A

**Comment by Tomasz-Kluczkowski** [comment]
Same on macOS 26.1 (25B78) (and on pgadmin 9.9)

**Comment by classychizzy** [comment]
i have a similar issue. pls how do i resolve this, i have moved pgadmin from my download folder yet it's not working

**Comment by tsoltan** [comment]
Same issue 26.1 (25B78) pgadmin 9.10

**Comment by Tomasz-Kluczkowski** [comment]
I caved in and just downloaded 9.10 version and replaced previous one manually on macOS without  using the built-in update option

**Comment by matthewbordas** [comment]
@Tomasz-Kluczkowski good call: I went to https://www.pgadmin.org/download/ and downloaded it directly which worked, thanks!

**Comment by matthewbordas** [comment]
Looks like this is resolved now, thanks!

**Comment by anilsahoo20** [comment]
We’ve officially fixed the "Read-only volume" issue on macOS! This fix ensures that your future updates will be seamless and automatic.
Action Required: To benefit from this fix, you must perform a one-time manual upgrade:
1. Delete your current pgAdmin 4 app.
2. Install the new v9.12 from [here](https://www.pgadmin.org/download/pgadmin-4-macos/).
3. Move pgadmin4 app to Applications folder

Once you are on v9.12, all future updates will work as expected. Thanks for sticking with us!

**Comment by jonty3** [comment]
Still getting this now on v9.12. Will manually download then reinstall for now.

**Comment by EXJakub** [comment]
@anilsahoo20 the same issue persists with in 9.13.
